name: cryptotracker
description: "Crypto Tracker - Track your cryptocurrency investments"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Image Handling - ANDROID BUILD FIX: Stable versions
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.17

  # Responsive Design - ANDROID BUILD FIX: Compatible version 
  sizer: ^3.1.3

  # Storage & Persistence
  shared_preferences: ^2.2.2

  # Networking - ANDROID BUILD FIX: Stable versions
  dio: ^5.9.0
  connectivity_plus: ^6.1.5

  # Data Visualization - ANDROID BUILD FIX: Compatible version
  fl_chart: ^0.69.2

  # UI Enhancement
  fluttertoast: ^8.2.4

  # Typography
  google_fonts: ^6.1.0

  # UUID generation for anonymous transactions
  uuid: ^4.4.0

  # WASM-compatible web support
  logger: ^2.4.0

  # File operations for Android downloads - ANDROID BUILD FIX: Compatible versions
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  
  web: any
  universal_html: ^2.2.4
  supabase_flutter: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
